### ISSUE TITLE
Incorrect FTP address to get a sample file described in Readme

### ISSUE THREAD

**Issue by hyunsungkim** [martinobdl/ITCH#7]
I found the command to obtain a sample file should be as follows
`wget ftp://anonymous:@emi.nasdaq.com/ITCH/Nasdaq\ PSX\ ITCH/20190327.PSX_ITCH_50.gz -P ./data/binary`
It seems the directory's name has been changed to `Nasdaq PSX ITCH` from `PSX_ITCH`

**Comment by martinobdl** [comment]
yes, you are right. it seems that the directory's name has been changed. 
Thanks, it will be updated in the README
